//! `loom config` subcommand: init / show / get / set / path
//!
//! Manages the loom.toml configuration file. The TOML is the single source
//! of truth; `get` / `set` parse and update it via dotted-path keys like
//! `node.path` or `python.venv`.

use crate::config::Config;
use anyhow::{bail, Context, Result};
use colored::*;
use std::path::PathBuf;
use std::process::Command;

#[derive(clap::Subcommand, Debug)]
pub enum ConfigCmd {
    /// Initialize loom.toml (auto-detect node / python executables on PATH)
    Init {
        /// Overwrite existing loom.toml
        #[arg(long)]
        force: bool,
        /// Override Node executable path (skips auto-detection)
        #[arg(long)]
        node_path: Option<String>,
        /// Override Python executable path (skips auto-detection)
        #[arg(long)]
        python_path: Option<String>,
    },
    /// Show current effective configuration
    Show,
    /// Print a single config value (dotted key)
    Get { key: String },
    /// Set a single config value and write back to loom.toml
    Set {
        key: String,
        value: String,
        /// Skip the confirmation prompt for path changes
        #[arg(long, short = 'y')]
        yes: bool,
    },
    /// Print path to the active loom.toml
    Path,
}

pub fn run(cmd: ConfigCmd, cli_root: Option<&str>) -> Result<()> {
    match cmd {
        ConfigCmd::Init {
            force,
            node_path,
            python_path,
        } => init(force, node_path, python_path),
        ConfigCmd::Show => show(cli_root),
        ConfigCmd::Get { key } => get(&key, cli_root),
        ConfigCmd::Set { key, value, yes } => set(&key, &value, yes, cli_root),
        ConfigCmd::Path => {
            let p = config_path(cli_root);
            println!("{}", p.display());
            Ok(())
        }
    }
}

// ----- path resolution -----

fn config_path(cli_root: Option<&str>) -> PathBuf {
    // loom.toml is always read from loom.exe's directory — never from
    // cfg.root(). Otherwise setting `root` would orphan the config file
    // (chicken-and-egg: the new root doesn't have a loom.toml yet).
    if let Some(p) = cli_root {
        return PathBuf::from(p);
    }
    if let Ok(v) = std::env::var("LOOM_CONFIG") {
        return PathBuf::from(v);
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
            return parent.join("loom.toml");
        }
    }
    PathBuf::from("loom.toml")
}

fn load_or_init(cli_root: Option<&str>) -> Result<Config> {
    if let Some(p) = cli_root {
        return Config::load(Some(std::path::Path::new(p)));
    }
    Config::load(std::env::var("LOOM_CONFIG").ok().as_deref().map(std::path::Path::new))
}

// ----- subcommand impls -----

fn init(
    force: bool,
    node_path: Option<String>,
    python_path: Option<String>,
) -> Result<()> {
    let exe = std::env::current_exe().context("locating loom.exe")?;
    let root = exe
        .parent()
        .map(|p| p.to_path_buf())
        .context("loom.exe has no parent directory")?;

    let toml_path = root.join("loom.toml");

    if toml_path.exists() && !force {
        bail!(
            "loom.toml already exists at {}\n  hint: pass --force to overwrite",
            toml_path.display()
        );
    }

    // Auto-detect node.exe and python.exe on PATH. Skip version-manager
    // shims (anything under "mise\shims" on Windows) so we point at a
    // real interpreter, not a wrapper.
    let detected_node = match node_path {
        Some(s) => Some(PathBuf::from(s)),
        None => detect_real_executable("node"),
    };
    let detected_python = match python_path {
        Some(s) => Some(PathBuf::from(s)),
        None => detect_real_executable("python"),
    };

    let node_line = match &detected_node {
        Some(p) => format!("# path = \"{}\"\n", escape_for_toml(&p.to_string_lossy())),
        None => String::new(),
    };
    let python_line = match &detected_python {
        Some(p) => format!("# path = \"{}\"\n", escape_for_toml(&p.to_string_lossy())),
        None => String::new(),
    };

    let content = format!(
        r#"# Loom configuration
# Generated by `loom config init` on {date}.
# Uncomment any line below and edit to override the default. Anything
# left commented (or absent) keeps the default behavior.
#
# `root` resolution order (highest priority first):
#   1. `root` field in this file (uncomment and set below)
#   2. $LOOM_DIR environment variable
#   3. C:\Loom on Windows / ~/Loom elsewhere
#   4. loom.exe's directory (last-resort fallback)

# root = "C:\Loom"

# HTTP/HTTPS proxy URL. When set, loom sets HTTP_PROXY / HTTPS_PROXY for
# commands it runs. When unset, loom doesn't touch proxy env vars — it
# relies on whatever the calling shell already has.
# proxy_url = "http://127.0.0.1:7897"

[node]
# Absolute path to node.exe. loom calls this directly — no version
# manager (mise / nvm / fnm) required. Uncomment and edit, or run
#   loom config set node.path "C:\Path\to\node.exe"
{node_line}# Project directory, relative to root. Default: "nodeapp". Rename freely
# (e.g. "mynode", "frontend-tools").
project_dir = "nodeapp"

[python]
# Absolute path to python.exe. loom uses it to create the venv and to
# rebuild after a Python interpreter change. Uncomment and edit, or run
#   loom config set python.path "C:\Path\to\python.exe"
{python_line}project_dir = "pythonapp"
# Path to virtualenv, relative to project_dir. Set to null to use ".venv".
venv = ".venv"

[shims]
# Subdirectory under root for all shims — both Node and Python. Empty
# (default) means shims live in <root>/ alongside loom.exe — no
# extra PATH entry needed, just add <root>/ to PATH once. Set to a
# non-empty value (e.g. "shims") to keep shims in their own dir.
dir = ""
"#,
        date = chrono_like_date(),
        node_line = node_line,
        python_line = python_line,
    );

    std::fs::write(&toml_path, content)
        .with_context(|| format!("writing {}", toml_path.display()))?;

    println!("{} config written: {}", "ok".green().bold(), toml_path.display());
    println!();
    println!("  loom root     {}", root.display());
    if let Some(p) = &detected_node {
        println!("  node path       {}", p.display());
    } else {
        println!(
            "  node path       {} (not detected — set it with `loom config set node.path`)",
            "<missing>".yellow()
        );
    }
    if let Some(p) = &detected_python {
        println!("  python path     {}", p.display());
    } else {
        println!(
            "  python path     {} (not detected — set it with `loom config set python.path`)",
            "<missing>".yellow()
        );
    }
    println!();
    println!("Next steps:");
    println!("  loom node install <pkg>...");
    println!("  loom node shim add <name>");
    Ok(())
}

fn show(cli_root: Option<&str>) -> Result<()> {
    let cfg = load_or_init(cli_root)?;
    let p = config_path(cli_root);
    println!("{} {}", "config file:".bold(), p.display());
    if !p.exists() {
        println!(
            "  {} (not yet created — run `loom config init`)",
            "default".yellow()
        );
    }
    println!();
    crate::cmd::info::run(&cfg)
}

fn get(key: &str, cli_root: Option<&str>) -> Result<()> {
    let cfg = load_or_init(cli_root)?;
    let value = resolve_get(&cfg, key)?;
    println!("{value}");
    Ok(())
}

fn set(key: &str, value: &str, yes: bool, cli_root: Option<&str>) -> Result<()> {
    let _ = load_or_init(cli_root)?;
    let p = config_path(cli_root);
    let mut toml_str = std::fs::read_to_string(&p)
        .with_context(|| format!("reading {} — run `loom config init` first", p.display()))?;

    // Switching the node or python interpreter invalidates native
    // dependencies. Warn the user and ask for confirmation.
    if is_dangerous_key(key) {
        let cfg = load_or_init(cli_root)?;
        let old = resolve_get(&cfg, key).unwrap_or_else(|_| "<unset>".to_string());
        if old == value {
            println!(
                "{} {} already at {} — nothing to do",
                "ok".green().bold(),
                key.cyan(),
                value
            );
            return Ok(());
        }
        println!(
            "{}",
            "About to switch runtime interpreter — this is a BREAKING change."
                .yellow()
                .bold()
        );
        println!("  {} {}", key.cyan(), format!("{} → {}", old, value).bold());
        println!();
        if key == "node.path" {
            println!(
                "  After this change, run `loom node rebuild` to recompile\n  \
                 native modules (.node files) against the new V8 ABI.\n  \
                 Pure-JS packages will keep working; native modules (sqlite3,\n  \
                 bcrypt, sharp, etc.) will fail until you rebuild."
            );
        } else if key == "python.path" {
            println!(
                "  After this change, run `loom python rebuild` to reinstall\n  \
                 all packages — wheels are bound to the Python ABI, so the\n  \
                 existing venv contents are effectively unusable."
            );
        }
        println!();
        if !yes && !confirm("Continue? [y/N]")? {
            println!("aborted — no changes written");
            return Ok(());
        }
    }

    apply_set(&mut toml_str, key, value)?;
    std::fs::write(&p, &toml_str).with_context(|| format!("writing {}", p.display()))?;
    let new_cfg = Config::load(Some(p.as_path()))?;
    let new_value = resolve_get(&new_cfg, key)?;
    if is_dangerous_key(key) {
        println!(
            "{} {} = {}\n  {}",
            "set".green().bold(),
            key.cyan(),
            new_value,
            "remember to run `loom <lang> rebuild` to restore dependencies".yellow()
        );
    } else {
        println!("{} {} = {}", "set".green().bold(), key.cyan(), new_value);
    }
    Ok(())
}

/// Keys that, when changed, invalidate previously-installed dependencies.
fn is_dangerous_key(key: &str) -> bool {
    matches!(key, "node.path" | "python.path")
}

/// Read a single y/N confirmation from stdin. Empty input defaults to N.
fn confirm(prompt: &str) -> Result<bool> {
    use std::io::Write;
    print!("{prompt} ");
    std::io::stdout().flush().ok();
    let mut line = String::new();
    std::io::stdin().read_line(&mut line)?;
    Ok(matches!(line.trim().to_ascii_lowercase().as_str(), "y" | "yes"))
}

// ----- dotted-path get / set -----

fn resolve_get(cfg: &Config, key: &str) -> Result<String> {
    Ok(match key {
        "proxy_url" => cfg
            .proxy_url
            .clone()
            .unwrap_or_else(|| "(from environment)".to_string()),
        "root" => cfg.root().display().to_string(),
        "node.path" => cfg
            .node
            .path
            .as_ref()
            .map(|p| p.display().to_string())
            .unwrap_or_else(|| "null".to_string()),
        "node.project_dir" => cfg.node.project_dir.clone(),
        "python.path" => cfg
            .python
            .path
            .as_ref()
            .map(|p| p.display().to_string())
            .unwrap_or_else(|| "null".to_string()),
        "python.project_dir" => cfg.python.project_dir.clone(),
        "python.venv" => cfg
            .python
            .venv
            .clone()
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "null".to_string()),
        "shims.dir" => cfg.shims.dir.clone(),
        other => bail!(
            "unknown config key: `{other}`\n  valid keys: proxy_url, root, node.path, node.project_dir, python.path, python.project_dir, python.venv, shims.dir"
        ),
    })
}

/// Apply a set operation by rewriting the relevant line in the raw TOML text.
fn apply_set(toml_str: &mut String, key: &str, value: &str) -> Result<()> {
    let (section, field) = split_key(key)?;
    let value_str = quote_value(value);

    let mut current_section = String::new();
    let mut replaced = false;
    let mut out = String::with_capacity(toml_str.len());
    for line in toml_str.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            current_section = trimmed[1..trimmed.len() - 1].to_string();
            out.push_str(line);
            out.push('\n');
            continue;
        }
        if current_section == section
            && !trimmed.starts_with('#')
            && trimmed.starts_with(field)
            && trimmed[field.len()..].trim_start().starts_with('=')
        {
            out.push_str(&format!("{field} = {value_str}\n"));
            replaced = true;
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }

    if !replaced {
        if !section.is_empty() {
            if !toml_str.contains(&format!("[{section}]")) {
                bail!(
                    "section [{section}] not found in loom.toml — re-run `loom config init` first"
                );
            }
            let mut out2 = String::new();
            let mut inserted = false;
            for line in toml_str.lines() {
                out2.push_str(line);
                out2.push('\n');
                if !inserted && line.trim() == format!("[{section}]") {
                    out2.push_str(&format!("{field} = {value_str}\n"));
                    inserted = true;
                }
            }
            *toml_str = out2;
        } else {
            insert_top_level(toml_str, &format!("{field} = {value_str}"));
        }
    } else {
        *toml_str = out;
    }
    Ok(())
}

fn insert_top_level(toml_str: &mut String, line: &str) {
    if let Some(rel) = toml_str.find("\n[") {
        let pos = rel + 1;
        toml_str.insert_str(pos, &format!("{line}\n"));
    } else {
        if !toml_str.ends_with('\n') {
            toml_str.push('\n');
        }
        toml_str.push_str(line);
        toml_str.push('\n');
    }
}

fn split_key(key: &str) -> Result<(&str, &str)> {
    if let Some((sec, field)) = key.split_once('.') {
        Ok((sec, field))
    } else {
        if matches!(key, "proxy_url" | "root") {
            Ok(("", key))
        } else {
            bail!("invalid key `{key}` — use dotted form like `node.path`")
        }
    }
}

fn quote_value(value: &str) -> String {
    if value == "null" {
        return "\"\"".to_string();
    }
    let escaped = escape_for_toml(value);
    format!("\"{escaped}\"")
}

fn escape_for_toml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// ----- auto-detection helpers -----

/// Walk PATH looking for `binary`, return the first match. Skips
/// `mise\shims` so we point at a real interpreter, not a wrapper.
fn detect_real_executable(binary: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        // Skip version-manager shims.
        let dir_str = dir.to_string_lossy();
        if dir_str.contains("mise") && dir_str.contains("shims") {
            continue;
        }
        #[cfg(windows)]
        let candidates = [format!("{binary}.exe"), format!("{binary}.cmd"), binary.to_string()];
        #[cfg(not(windows))]
        let candidates = [binary.to_string()];
        for c in candidates {
            let p = dir.join(&c);
            if p.is_file() {
                return Some(p);
            }
        }
    }
    // Last resort: try `where` / `which` — might find something PATH
    // walking missed (e.g. WindowsApps alias).
    let cmd_name = if cfg!(windows) { "where" } else { "which" };
    if let Ok(out) = Command::new(cmd_name).arg(binary).output() {
        if out.status.success() {
            let s = String::from_utf8_lossy(&out.stdout);
            for line in s.lines() {
                let p = PathBuf::from(line.trim());
                let s = p.to_string_lossy();
                if s.contains("mise") && s.contains("shims") {
                    continue;
                }
                if p.is_file() {
                    return Some(p);
                }
            }
            // Fall back to the first line even if it's a shim — better than nothing.
            if let Some(line) = s.lines().next() {
                let p = PathBuf::from(line.trim());
                if p.is_file() {
                    return Some(p);
                }
            }
        }
    }
    None
}

fn chrono_like_date() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let day = secs / 86_400;
    let (y, m, d) = civil_from_days(day as i64);
    format!("{y:04}-{m:02}-{d:02}")
}

fn civil_from_days(z: i64) -> (i32, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i32 + (era as i32) * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}
